version: '3.4'

networks:
    demoaggregationapp:

services:
  aggregationappdb:
    container_name: aggregation-app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1234@
    ports:
     - 8002:1433
    networks:
     - demoaggregationapp

  aggregationapp:
    container_name: aggregation-app
    image: ${DOCKER_REGISTRY-}aggregationapp
    build:
      context: .
      dockerfile: AggregationApp/Dockerfile
    ports:
     - 8001:80
    depends_on: 
     - aggregationappdb
    environment:
     - DB_HOST=aggregationappdb
     - DB_NAME=AggregationDB
     - DB_SA_PASSWORD=Password1234@
     - DB_PORT=1433
    networks:
     - demoaggregationapp
